services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/uriel-ruiz/Esp32Mongo
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://UrielAlfonso:kRtCAJkaAuOpIpOJ@cluster0.xrixs.mongodb.net/BasePryEsp32?retryWrites=true&w=majority&appName=Cluster0
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"